### ISSUE TITLE
Incorrect padding by trailing excess =

### ISSUE THREAD

**Issue by niemyjski** [neosmart/UrlBase64#4]
I noticed several .net as well as other languages implementations remove the `=` at the end. Perhaps this shouldn't be done as some services fail without it (file stack requires a policy with base64).  I haven't yet looked into `RFC4648` to see if this allowed or not. But I did find this old issue here: https://stackoverflow.com/questions/1228701/code-for-decoding-encoding-a-modified-base64-url

which lead me to do 

```c#
string policy = UrlBase64.Encode(Encoding.UTF8.GetBytes(json));
policy = policy.PadRight(policy.Length + (4 - policy.Length % 4) % 4, '=');      
```

Please note here is the JSON string which should have the extra padding: `{"call":["pick","read","stat","write","writeUrl","store","convert","remove","exif"],"path":"private/organization/537650f3b77efe23a47914f3/contact/5a677e50dbb7bf20c4e1f431d/attachments/map.gif","expiry":1516827600}`

The thing is some online decoders account for this and decode anyways. Perhaps we need to look into strict encoding?

**Comment by mqudsi** [comment]
Thanks for taking the time to file this issue, @niemyjski 

We did consider this when the library was being developed but ultimately ruled in favor of stripping trailing `=` padding because most cases of web-safe base64 would ultimately involve encoding and decoding being performed by the same library. The decode method should be compatible with padded and stripped base64, but the encode method currently only generates stripped output, mainly because the entire purpose behind url-safe base64 is for embedding in URLs, where extraneous characters would be frowned upon.

I'll add an option to keep the trailing padding.

**Comment by niemyjski** [comment]
Thanks! But having trailing == is still valid for querything/url segments to my knowledge   
  

  
  

  
  
>

**Comment by mqudsi** [comment]
It certainly is, it just may not be desirable default behavior. The RFC spec says that if the size is known ahead of time/can be determined, the padding may be left off in section 3.2:

>   In some circumstances, the use of padding ("=") in base-encoded data
>   is not required or used.  In the general case, when assumptions about
>   the size of transported data cannot be made, padding is required to
>   yield correct decoded data.

This is fixed in https://github.com/neosmart/UrlBase64/commit/957165fbba71f7818f02fac4977b019d8cdebc57, https://github.com/neosmart/UrlBase64/commit/f608a4af3d9fe0648d0ff6d55f856136b5e40ebb, and https://github.com/neosmart/UrlBase64/commit/a579e5cb701753f6b79f8cbb543b73f23d6851c1

Does this adequately address your concerns?

**Comment by niemyjski** [comment]
Yes, looks good! I wonder if to be safe the not so desirable version should be used? Better it works everywhere than not.

**Comment by niemyjski** [comment]
Any chance we could get a release out for this.

**Comment by mqudsi** [comment]
Yup. There was some documentation that needed to be written prior to release, but v0.1.2 is now out with this feature.

**Comment by niemyjski** [comment]
Awesome thanks! Can you please create a github tag for 0.1.2 :)

**Comment by mqudsi** [comment]
https://github.com/neosmart/UrlBase64/releases
