### ISSUE TITLE
decoding using ReadOnlySpan<T> 

### ISSUE THREAD

**Issue by flightlex** [neosmart/UrlBase64#6]
decoding large amount of data cannot be possible because of StackOverflowException being thrown at 'stackalloc byte[decodedLength];'. Please fix it and avoid using `stackalloc` because of it's restrictions!!!

**Comment by mqudsi** [comment]
How big of data are you decoding?!

**Comment by flightlex** [comment]
> How big of data are you decoding?!

12kb of pure base64 in average

**Comment by flightlex** [comment]
also, there is no sense of stack allocation, if you still re-allocate it to heap using .ToArray() method

**Comment by Folleach** [comment]
I think the size of the input `ReadOnlySpan<char>` can be something in the region of 100 MB in our case.  
This is the reason why we try to reuse memory using span's

**Comment by mqudsi** [comment]
I've ~~added an option to~~ changed the code to only use `stackalloc` in case the allocation is 1KiB or less in 19182bca4b8dc2dafe0ae4990998871d4f6b0be5.

@flightlex 
> also, there is no sense of stack allocation, if you still re-allocate it to heap using .ToArray() method

Actually, it's not that simple. When encoding or decoding content with the trailing `=` discarded (which is the default encoding mode to prevent the output from requiring any escaping when used as a uri), we don't know ahead of time the length of the output. Since .NET doesn't offer a way to truncate an array without reallocating everything, if we didn't use stack allocation there would be *two* heap allocations instead of one. 

I think it _should_ be possible to figure out from the start the final size depending on the specified padding policy (for encode) or just as a function of the input length + skipping ahead to count the number of trailing `=` signs for UrlBase64Decode(), I haven't sat down to do the math in a way that convinces me of the answer. If we're able to do that, we can just allocate once on the heap from the start.

@folleach 
> I think the size of the input ReadOnlySpan<char> can be something in the region of 100 MB in our case.
> This is the reason why we try to reuse memory using span's

Can you tell me more about your use case? I never imagined that you would need to use url-safe base64 encoding for something that large, as it's quite over the limit for pretty much any web server or client. Are you using it in the POST body?

For your case, it would definitely be preferred to avoid *any* allocation at all. There are options here such as decoding in place (replacing the contents of the input buffer then returning a span pointing into the same buffer that was passed in) but for encoding the only option we'd be able to offer would be an api that calculates the length of the result (taking the padding policy into account) then an overload of `UrlBase64.Encode()` that takes a second parameter that's an array or span into which the content will be encoded. You can use stackalloc from the calling frame so no heap allocations are required for smaller invocations, but for larger encodes to the tune of 100 MiB or more the benefit would be that you can reuse the same buffer for multiple encodes, assuming you aren't just doing this once in the lifetime of your application (or such that it would make sense to hang on to a 100 MiB buffer without freeing that memory).

**Comment by flightlex** [comment]
> Can you tell me more about your use case?

His `our case` meant mine and his case, so i am able to answer for him. Our case doesn't even make any web requests. Its just a game's data storage encoding (no clue why the developer of the game encodes with UrlBase64, instead of the regular one). By the way 100mb is not even a limit, i am sure there are some people that have even more than 200mb of data. So library's limitations will definetely affect and probably even break the entire process.

> ..assuming you aren't just doing this once in the lifetime of your application

This is correct, so we'd actually appreciate decent fix and least allocations of this!!

And do you personally think there is any approach to measure the whole length of the final string at the beginning the the decoding? I could be searching and trying if this makes any sense :)

**Comment by mqudsi** [comment]
> And do you personally think there is any approach to measure the whole length of the final string at the beginning the the decoding? I could be searching and trying if this makes any sense :)

Yes, but this necessitated rewriting the entire encode pipeline. 

I've just released version `2.0.0-preview1` on nuget (it might take a few minutes to become visible) that now always calculates the final size up front (so no more slicing or double allocation regardless of the input/output length), and introduces new APIs that can be used to avoid allocations altogether. For best performance, you would want to use the routines that encode/decode to bytes, not string. There's an overload of both `Encode()` and `Decode()` that takes a buffer as a second parameter, it can perform the entire encode or decode operation allocation-free and return the result as a `Span<byte>` allocated from the passed in buffer, which can be re-used across calls.

You need to make sure Visual Studio or `dotnet` or `nuget` is set to include prereleases versions to upgrade to version `2.0.0-preview1` (as it's released as a beta release). Please let me know how this works for you, both in terms of bugs (should be no more crash), performance (should be tremendously better), and ergonomics of the API (it's not as simple as it was, but I think it's still pretty straight-forward).

All the methods have been extensively documented as well.

**Comment by mqudsi** [comment]
https://www.nuget.org/packages/UrlBase64/2.0.0-preview1

**Comment by flightlex** [comment]
thanks!! <3

**Comment by Folleach** [comment]
Thank you a lot!

With the new allocation-free API and partial reading, we were able to reduce memory consumption by 8 times during decode large objects
|                    Method |    Mean |    Error |   StdDev |       Gen0 |       Gen1 |      Gen2 |  Allocated |
|-------------------------- |--------:|---------:|---------:|-----------:|-----------:|----------:|-----------:|
| DecodeLargeObjectFromFile (Old) | 2.412 s | 0.0445 s | 0.0394 s | 39000.0000 | 16000.0000 | 5000.0000 | 1612.97 MB |
| DecodeLargeObjectFromFile (New) | 1.195 s | 0.0171 s | 0.0160 s |  4000.0000 |  3000.0000 | 3000.0000 |  204.1 MB |

In the version 0.1.2 we used your library to decode the whole huge array of bytes.  
In the version 1.0.1, this became impossible, so the implementation was rewritten for decoding in chunks, based on the base64 property when 3 bytes turn into 4 characters and vice versa.  
Then we used your new allocation-free api, which allowed us not to allocate new objects for chunks.  
Of course, we still have to allocate a large object, but we reduced memory traffic quite well.  
We'll test further :)

I also noticed that unsafe blocks were remove, and stackalloc were also remove.  
This is beautiful! Because previously I think it was possible to accidentally get a DOS attack to a web service that use UrlBase64. The potential presence of going beyond the boundaries of the array in unsafe blocks on the stack was also very frightening.  
I think the issue can be closed, thank you for your help!

**Comment by mqudsi** [comment]
You’re most welcome. Thanks for posting with the benchmarks - the memory numbers look much better! 

I considered adding a streaming/chunking option but wasn’t sure if it was required at this time.
